services:
  postgres:
    image: postgres:15-alpine
    container_name: workflow-db-prod
    environment:
      POSTGRES_USER: workflow_user
      POSTGRES_PASSWORD: workflow_password
      POSTGRES_DB: workflow_db
    ports:
      - "15432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - workflow-network
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.prod
    container_name: workflow-frontend-prod
    ports:
      - "3000:80"
    networks:
      - workflow-network
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.prod
    container_name: workflow-backend-prod
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: workflow_user
      POSTGRES_PASSWORD: workflow_password
      POSTGRES_DB: workflow_db
      NODE_ENV: production
    ports:
      - "4000:4000"
    networks:
      - workflow-network
    restart: unless-stopped

volumes:
  postgres_data_prod:

networks:
  workflow-network:
    driver: bridge